mutation CaptureEmail($email: Sting!) {
    captureEmail (email: $email) {
        id
        email
    }
}

mutation Signup($id: String!, $fistname: String!,
$lastname: String!, $password: String!) {
    signup(id: $id, firstname: $firstname, lastname: $lastname, password: $password) {
        token
        user {
            id
            email
        }
    }
}